bmFtZTogaGV4bGV0LWNoZWNrCgpvbjoKICBwdXNoOgogICAgYnJhbmNoZXM6
CiAgICAgIC0gbWFzdGVyCgplbnY6CiAgUFJPSkVDVF9JTUFHRTogaGV4bGV0
cHJvamVjdHMvanNfbDFfYnJhaW5fZ2FtZXM0X3Byb2plY3QKCmpvYnM6CiAg
YnVpbGQ6CiAgICBydW5zLW9uOiB1YnVudHUtbGF0ZXN0CiAgICBzdGVwczoK
ICAgICAgLSB1c2VzOiBhY3Rpb25zL2NoZWNrb3V0QHYyCgogICAgICAtIG5h
bWU6IEhleGxldCBwcm9qZWN0IGNoZWNrCiAgICAgICAgdXNlczogaGV4bGV0
L3Byb2plY3QtYWN0aW9uQG1hc3RlcgogICAgICAgIHdpdGg6CiAgICAgICAg
ICBwcm9qZWN0X2ltYWdlOiAke3sgZW52LlBST0pFQ1RfSU1BR0UgfX0KCg==
